[package]
name = "advent-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
average = "0.15.1"
itertools = "0.13.0"
num = "0.4.3"
num-traits = "0.2.19"
pathfinding = "4.12.0"
rayon = "1.10.0"
regex = "1.11.1"
